login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path("signin", views.signin, name="signin"),
    path("signup",views.signup,name="signup"),
    path('logout', views.logout, name='logout'),
    path("profile",views.profile,name="profile"),
    path("profile_password",views.profile_password,name="profile_password"),
    path("bill",views.bill,name="bill"),
    path("security",views.security,name="security"),

    # path('forget',views.forgot_password,name='forget'),
]

loginregister/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path("signin", views.signin, name="signin"),
    path("signup", views.signup, name="signup"),
    path('logout', views.logout, name='logout'),
    path("bill", views.bill, name="bill"),
    path("forgot_password",views.forgot_password,name='forgot_password'),
    path("is_otp_expired",views.is_otp_expired,name="is_otp_expired"),
    path("handle_otp",views.handle_otp,name="handle_otp"),
    path("password_update",views.password_update,name="password_update"),
    path("profile_page", views.profile_page, name="profile_page"),
    path("profile_password", views.profile_password, name="profile_password"),
    path("profile_forgot_password", views.profile_forgot_password, name='profile_forgot_password'),
    path("profile_handle_otp", views.profile_handle_otp, name="profile_handle_otp"),
    path("profile_password_update", views.profile_password_update, name="profile_password_update"),
    path('verify_email/<str:token>/', views.verify_email, name='verify_email'),
    path('resend_otp/',views.resend_otp,name="resend_otp"),
    path('profile_resend_otp/',views.profile_resend_otp,name="profile_resend_otp"),
    path('delete_account/',views.delete_account, name='delete_account'),
    path('delete_verify_email/<str:token>/', views.delete_verify_email, name='delete_verify_email'),
    path('check_username',views.check_username,name="check_username"),
    path('check_email',views.check_email,name="check_email"),
    path('check_currentpassword',views.check_currentpassword,name="check_currentpassword"),
]

mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('',views.home,name='home'),
    path("temp_view/<int:template_card_id>/",views.temp_view,name="temp_view"),
    path("morenormal",views.moreNormal,name="morenormal"),
    path("morepremium",views.morePremium,name="morepremium"),
    path('pay/<int:template_id>/',views.pay,name='pay'),
    path("coupen/<int:id>/",views.coupen,name='coupen'),
    path("delcoupen/<int:template_id>/",views.delcoupen,name='delcoupen'),
    path("checkout/<int:id>/",views.checkout,name='checkout'),
    path("success/",views.success,name="success"),
    path('failed/',views.paymentfailed,name="failed"),
    path('somethingwentwrong/',views.somethingwentwrong,name="somethingwentwrong"),
]

tempbuys/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/',include('customadmin.urls')),
    
    path('dfadmin/', admin.site.urls),
    path('',include('mainapp.urls')),
    path('loginregister',include('loginregister.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/profile/bill.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" integrity="sha256-2XFplPlrFClt0bIdPgpz8H7ojnk10H69xRqd9+uTShA=" crossorigin="anonymous" />
<style>
    body{margin-top:20px;
background-color:#4a546a;
color:#69707a;
}
.img-account-profile {
    height: 10rem;
}
.rounded-circle {
    border-radius: 50% !important;
}
.card {
    box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
}
.card .card-header {
    font-weight: 500;
}
.card-header:first-child {
    border-radius: 0.35rem 0.35rem 0 0;
}
.card-header {
    padding: 1rem 1.35rem;
    margin-bottom: 0;
    background-color: rgba(33, 40, 50, 0.03);
    border-bottom: 1px solid rgba(33, 40, 50, 0.125);
}
.form-control, .dataTable-input {
    display: block;
    width: 100%;
    padding: 0.875rem 1.125rem;
    font-size: 0.875rem;
    font-weight: 400;
    line-height: 1;
    color: #69707a;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #c5ccd6;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    border-radius: 0.35rem;
    transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
}

.nav-borders .nav-link.active {
    color: #f39c12;
    border-bottom-color: #f39c12;
}
.nav-borders .nav-link {
    color: #fff;
    border-bottom-width: 0.125rem;
    border-bottom-style: solid;
    border-bottom-color: transparent;
    padding-top: 0.5rem;
    padding-bottom: 0.5rem;
    padding-left: 0;
    padding-right: 0;
    margin-left: 1rem;
    margin-right: 1rem;
}
.fa-2x {
    font-size: 2em;
}

.table-billing-history th, .table-billing-history td {
    padding-top: 0.75rem;
    padding-bottom: 0.75rem;
    padding-left: 1.375rem;
    padding-right: 1.375rem;
}
.table > :not(caption) > * > *, .dataTable-table > :not(caption) > * > * {
    padding: 0.75rem 0.75rem;
    background-color: var(--bs-table-bg);
    border-bottom-width: 1px;
    box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg);
}

.border-start-primary {
    border-left-color: #f39c12 !important;
/* <!--   border-left-color: #0061f2 !important; --> */
}
.border-start-secondary {
    border-left-color: #f39c12 !important;
/* <!--    border-left-color: #6900c7 !important; --> */
}
.border-start-success {
    border-left-color: #00ac69 !important;
}
.border-start-lg {
    border-left-width: 0.25rem !important;
}
.h-100 {
    height: 100% !important;
}
</style>
</head>
<body>

<div class="container-xl px-4 mt-4">
    <!-- Account page navigation-->
    <nav class="nav nav-borders">
        <a class="nav-link active ms-0" href="{% url 'mainapp:home' %}">Home</a>
        <a class="nav-link ms-0" href="{% url 'login:profile_page' %}">Profile</a>
        <a class="nav-link active" href="{% url 'login:bill' %}">Billing</a>
        <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
    </nav>
    <hr class="mt-0 mb-4">
    <div class="row">
        {% for order in orders %}
        {% for payment_success in payment_success_list %}
        {% if payment_success.order == order %}
        <div class="col-sm-4 mb-4">
            <!-- Billing card 1-->
            <div class="card h-100 border-start-lg border-start-primary">
                <div class="card-body">
                    <div class="small text-muted">Order Date</div>
                    <div class="h3">{{ payment_success.payment_date|date:"m/d/Y" }}</div>
                    <!-- <div class="h3">{{ payment_success.payment_date }}</div> -->
<!--                    <a class="text-arrow-icon small" href="#!">-->
<!--                        Switch to yearly billing-->
<!--                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>-->
<!--                    </a>-->
                </div>
            </div>
        </div>
        <div class="col-sm-4 mb-4">
            <!-- Billing card 2-->
            <div class="card h-100 border-start-lg border-start-secondary">
                <div class="card-body">
                    <div class="small text-muted">Next payment due</div>
                    <div class="h3">{{ payment_success.expiry_date|date:"m/d/Y" }}</div>
<!--                    <a class="text-arrow-icon small text-secondary" href="#!">-->
<!--                        View payment history-->
<!--                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>-->
<!--                    </a>-->
                </div>
            </div>
        </div>
        <div class="col-sm-4 mb-4">
            <!-- Billing card 3-->
            <div class="card h-100 border-start-lg border-start-success">
                <div class="card-body">
                    <div class="small text-muted">Current plan</div>
                    <div class="h3 d-flex align-items-center">{{order.template_name}}</div>
<!--                    <a class="text-arrow-icon small text-success" href="#!">-->
<!--                        Upgrade plan-->
<!--                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>-->
<!--                    </a>-->
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    {% endfor %}
    </div>
    <!-- Payment methods card-->
    <div class="card card-header-actions mb-4">
        <div class="card-header">
            Payment Methods
<!--            <button class="btn btn-sm btn-primary" type="button">Add Payment Method</button>-->
        </div>
        <div class="card-body px-0">
            <!-- Payment method 1-->
            <div class="d-flex align-items-center justify-content-between px-4">
                <div class="d-flex align-items-center">
                     <i class="fab fa-cc-visa fa-2x cc-color-visa"></i>
                    <div class="ms-4">
                        <div class="small">Visa ending in 1234</div>
                        <div class="text-xs text-muted">Expires 04/2024</div>
                    </div>
                </div>
                <div class="ms-4 small">
                    <div class="badge bg-light text-dark me-3">Default</div>
                    <a href="#!">Edit</a>
                </div>
            </div>
            <hr>
            <!-- Payment method 2-->
            <div class="d-flex align-items-center justify-content-between px-4">
                <div class="d-flex align-items-center">
                    <i class="fab fa-cc-mastercard fa-2x cc-color-mastercard"></i>
                    <div class="ms-4">
                        <div class="small">Mastercard ending in 5678</div>
                        <div class="text-xs text-muted">Expires 05/2022</div>
                    </div>
                </div>
                <div class="ms-4 small">
                    <a class="text-muted me-3" href="#!">Make Default</a>
                    <a href="#!">Edit</a>
                </div>
            </div>
            <hr>
            <!-- Payment method 3-->
            <div class="d-flex align-items-center justify-content-between px-4">
                <div class="d-flex align-items-center">
                    <i class="fab fa-cc-amex fa-2x cc-color-amex"></i>
                    <div class="ms-4">
                        <div class="small">American Express ending in 9012</div>
                        <div class="text-xs text-muted">Expires 01/2026</div>
                    </div>
                </div>
                <div class="ms-4 small">
                    <a class="text-muted me-3" href="#!">Make Default</a>
                    <a href="#!">Edit</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Billing history card-->
    <div class="card mb-4">
        <div class="card-header">Billing History</div>
        <div class="card-body p-0">
            <!-- Billing history table-->
            <div class="table-responsive table-billing-history">
                <table class="table mb-0">
                    <thead>
                        <tr>
                            <th class="border-gray-200" scope="col">Transaction ID</th>
                            <th class="border-gray-200" scope="col">Date</th>
                            <th class="border-gray-200" scope="col">Amount</th>
                            <th class="border-gray-200" scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>#39201</td>
                            <td>06/15/2021</td>
                            <td>$29.99</td>
                            <td><span class="badge bg-light text-dark">Pending</span></td>
                        </tr>
                        <tr>
                            <td>#38594</td>
                            <td>05/15/2021</td>
                            <td>$29.99</td>
                            <td><span class="badge bg-success">Paid</span></td>
                        </tr>
                        <tr>
                            <td>#38223</td>
                            <td>04/15/2021</td>
                            <td>$29.99</td>
                            <td><span class="badge bg-success">Paid</span></td>
                        </tr>
                        <tr>
                            <td>#38125</td>
                            <td>03/15/2021</td>
                            <td>$29.99</td>
                            <td><span class="badge bg-success">Paid</span></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <div class="card mb-4">
        <div class="card-header">Billing History</div>
        <div class="card-body p-0">
            <!-- Billing history table -->
            <div class="table-responsive table-billing-history">
                <table class="table mb-0">
                    <thead>
                        <tr>
                            <th class="border-gray-200" scope="col">Transaction ID</th>
                            <th class="border-gray-200" scope="col">Purchase Date</th>
                            <th class="border-gray-200" scope="col">Expiry Date</th>
                            <th class="border-gray-200" scope="col">Next Payment Date</th>
                            <th class="border-gray-200" scope="col">Amount</th>
                            <th class="border-gray-200" scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for payment_success in payment_success_list %}
                            <tr>
                                <td>#{{ payment_success.order.order_id }}</td>
                                <td>{{ payment_success.payment_date|date:"m/d/Y" }}</td>
                                <td>{{ payment_success.expiry_date|date:"m/d/Y" }}</td>
                                <td>
                                    {% if payment_success.countdown > 0 %}
                                        {{ payment_success.expiry_date|date:"m/d/Y" }} (Next Payment)
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                                <td>${{ payment_success.order.final_amount }}</td>
                                <td>
                                    {% if payment_success.payment_status %}
                                        <span class="badge bg-success">Paid</span>
                                    {% else %}
                                        <span class="badge bg-light text-dark">Pending</span>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
</div>
</body>
</html>

templates/profile/profile_forgot_password.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bootstrap 5 Forgot Password</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
   <style>
   *{
  box-sizing: border-box;
}
body{
  margin: 0;
}
.title{
  max-width: 400px;
  margin: auto;
  text-align: center;
  font-family: "Poppins", sans-serif;
  h1{
    font-weight: bold;
  }
  p{
    font-size: 12px;
    color: #118a44;
    &.msg{
      color: initial;
      text-align: initial;
      font-weight: bold;
    }
  }
}

.otp-input-fields{
  margin: auto;
  background-color: white;
  box-shadow: 0px 0px 8px 0px #02025044;
  max-width: 400px;
  width: auto;
  display: flex;
  justify-content: center;
  gap: 10px;
  padding: 40px;

  input{
    height: 40px;
    width: 40px;
    background-color: transparent;
    border-radius: 4px;
    border: 1px solid #2f8f1f;
    text-align: center;
    outline: none;
    font-size: 16px;
    &::-webkit-outer-spin-button,
    &::-webkit-inner-spin-button {
      -webkit-appearance: none;
      margin: 0;
    }

    /* Firefox */
    &[type=number] {
      -moz-appearance: textfield;
    }
    &:focus{
      border-width: 2px;
      border-color: darken(#2f8f1f, 5%);
      font-size: 20px;
    }
  }
}

.result{
  max-width: 400px;
  margin: auto;
  padding: 24px;
  text-align: center;
  p{
    font-size: 24px;
    font-family: 'Antonio', sans-serif;
    opacity: 1;
    transition: color 0.5s ease;
    &._ok{
      color: green;
    }
    &._notok{
      color: red;
      border-radius: 3px;
    }
  }
}

button#resendButton {
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
  margin: auto;
}
  </style>
  </head>

  <body>


        <div class="container d-flex flex-column">
          <div class="row align-items-center justify-content-center min-vh-100">
            <div class="col-12 col-md-8 col-lg-4">
              <form action="{% url 'login:profile_handle_otp' %}" method="post" class="otp-form">
                {% csrf_token %}
                <div class="title">
                  <h1>OTP VERIFICATION</h1>
                  <p class="info">An OTP has been sent to <strong>{{ email }}</strong></p>
                  <a href="{% url 'login:profile_page' %}"><p class="info"><strong>Back to Profile!</strong></p></a>
                  {% for msg in messages %}
                  <p class="msg" style="font-size:20px;">{{ msg }}</p>
                  {% endfor %}
                </div>
                <div class="otp-input-fields">
                  <input type="hidden" name="email" value="{{ email }}">
                  <input type="number" class="otp__digit otp__field__1" name="otp_1" maxlength="1" oninput="moveToNext(this, 'otp__field__2')">
                  <input type="number" class="otp__digit otp__field__2" name="otp_2" maxlength="1" oninput="moveToNext(this, 'otp__field__3')">
                  <input type="number" class="otp__digit otp__field__3" name="otp_3" maxlength="1" oninput="moveToNext(this, 'otp__field__4')">
                  <input type="number" class="otp__digit otp__field__4" name="otp_4" maxlength="1" oninput="moveToNext(this, 'otp__field__5')">
                  <input type="number" class="otp__digit otp__field__5" name="otp_5" maxlength="1" oninput="moveToNext(this, 'otp__field__6')">
                  <input type="number" class="otp__digit otp__field__6" name="otp_6" maxlength="1">
                </div>
                <div class="mt-3 d-grid justify-content-center">
                  <button type="submit" class="btn" style="background-color:#ef6603; width:150px; color: white;"><strong>Submit OTP</strong></button>
                </div>
                
              </form>
              <button onclick="window.location.href='{% url 'login:profile_resend_otp' %}'" class="btn" id="resendButton" style="border: none;" disabled>Resend OTP <span id="timer"></span></button>
    
            </div>
          </div>
        </div>

            
        <script>
          document.addEventListener("DOMContentLoaded", function () {
              var timerDisplay = document.getElementById("timer");
              var resendButton = document.getElementById("resendButton");
              var seconds = 60;
        
              // Function to update the timer display and handle the "Resend" button
              function updateTimer() {
                  var minutes = Math.floor(seconds / 60);
                  var remainingSeconds = seconds % 60;
        
                  if (seconds === 0) {
                      timerDisplay.style.display = "none"; // Hide the timer when it reaches 0
                      resendButton.removeAttribute("disabled"); // Enable the "Resend" button
                  } else {
                      if (remainingSeconds < 10) {
                          remainingSeconds = "0" + remainingSeconds;
                      }
                      timerDisplay.textContent = minutes + ":" + remainingSeconds;
                      seconds--;
                      setTimeout(updateTimer, 1000); // Update the timer every second
                  }
              }
        
              updateTimer(); // Start the timer immediately
          });
        
           // Function to move to the next input field
           function moveToNext(currentInput, nextFieldClass) {
                var maxLength = parseInt(currentInput.getAttribute("maxlength"));
                var currentLength = currentInput.value.length;
        
                if (currentLength === maxLength) {
                  var nextField = document.getElementsByClassName(nextFieldClass)[0];
                  if (nextField) {
                    nextField.focus();
                  }
                }
              };
        
        
        </script>
        
        
          </body>
        
        </html> 